export const UI_TEXT = {
  ko: {
    settings: "설정",
    export: "Export",
    treeStructure: "트리 구조",
    uploadPdf: "PDF 업로드 및 분석",
    uploading: "업로드 중...",
    indexing: "분석 중...",
    complete: "완료!",
    files: "파일",
    analysisSettings: "분석 설정",
    documentDomain: "문서 도메인",
    responseLanguage: "답변 언어",
    useDeepTraversal: "Deep Traversal 사용",
    maxDepth: "최대 깊이 (Max Depth)",
    maxBranches: "브랜치 수 (Max Branches)",
    deepTraversalDesc: "트리를 탐색하여 관련 섹션만 선택",
    flatModeDesc: "전체 문서를 사용 (레거시)",
    domainOptimized: "선택한 도메인에 최적화된 분석을 제공합니다",
    languageOptimized: "AI가 선택한 언어로 답변합니다",
    newChat: "새 대화",
    noHistory: "기록이 없습니다.",
    welcomeTitle: "TreeRAG",
    welcomeDesc: "PDF 문서를 업로드하면 AI가 자동으로 구조화하여 분석합니다.\\n계층적 트리 구조로 문서를 탐색하고 정확한 답변을 제공합니다.",
    shortcutKey: "단축키:",
    newSession: "새 세션",
    typeMessage: "메시지를 입력하세요...",
    sessionDeleted: "세션이 삭제되었습니다",
    analysisComplete: "분석이 완료되었습니다!",
    uploadFailed: "업로드/분석 실패",
    treeLoaded: "트리 로드 완료",
    treeLoadFailed: "트리 로드 실패",
    markdownSaved: "Markdown 파일로 저장되었습니다",
    nodeSelected: "노드 선택됨",
    pdfOpen: "PDF 열기",
    general: "일반 문서",
    medical: "의료/임상 문서",
    legal: "법률/계약 문서",
    financial: "금융/재무 문서",
    academic: "학술/연구 논문",
    korean: "한국어",
    english: "English",
    japanese: "日本語",
    deepTraversal: "Deep Traversal 사용",
    flatMode: "Flat Mode 사용",
    maxDepthDesc: "트리 탐색 최대 깊이 (1-10)",
    maxBranchesDesc: "레벨당 탐색할 자식 노드 수 (1-10)",
    tip: "팁",
    tipMessage: "깊이와 브랜치 수를 줄이면 응답 속도가 빨라지지만 정보가 제한될 수 있습니다.",
    analyzing: "AI가 규정을 분석하고 있습니다...",
    selectedSection: "선택된 섹션",
    sectionDeselected: "섹션 선택 해제됨",
    sectionQuestion: "섹션에 대해 질문하기...",
    send: "전송",
    disclaimer: "AI 답변은 업로드된 문서에 기반하지만, 중요한 결정 시 반드시 원문을 재확인하시기 바랍니다.",
    closeTree: "트리 닫기",
    tipTreeClick: "팁: Shift + 클릭으로 섹션 선택 후 질문하기",
    deleteSession: "세션 삭제",
    openSidebar: "사이드바 열기",
    closeSidebar: "사이드바 닫기",
    processing: "처리 중...",
    copiedToClipboard: "클립보드에 복사되었습니다",
    copyFailed: "복사 실패",
    recentHistory: "최근 기록",
    comparisonAnalysis: "문서 비교 분석",
    comparisonTarget: "비교 대상",
    commonalities: "공통점",
    differences: "차이점",
    crossReferenceResolved: "Cross-reference 해결됨",
    crossReferenceDesc: "질문에서 {count}개의 참조가 감지되어 자동으로 컨텍스트에 추가되었습니다",
    page: "페이지",
    searchPlaceholder: "대화 검색...",
    searchResults: "검색 결과",
    noSearchResults: "검색 결과가 없습니다",
    performance: "성능 모니터링",
    totalQueries: "총 질의 수",
    avgResponseTime: "평균 응답 시간",
    avgContextSize: "평균 컨텍스트 크기",
    deepTraversalUsage: "Deep Traversal 사용률",
    recentQueries: "최근 질의",
    tokens: "토큰",
    seconds: "초"
  },
  en: {
    settings: "Settings",
    export: "Export",
    treeStructure: "Tree View",
    uploadPdf: "Upload & Analyze PDF",
    uploading: "Uploading...",
    indexing: "Analyzing...",
    complete: "Complete!",
    files: "files",
    analysisSettings: "Analysis Settings",
    documentDomain: "Document Domain",
    responseLanguage: "Response Language",
    useDeepTraversal: "Use Deep Traversal",
    maxDepth: "Max Depth",
    maxBranches: "Max Branches",
    deepTraversalDesc: "Navigate tree to select relevant sections only",
    flatModeDesc: "Use entire document (legacy)",
    domainOptimized: "Provides analysis optimized for selected domain",
    languageOptimized: "AI responds in selected language",
    newChat: "New Chat",
    noHistory: "No history.",
    welcomeTitle: "TreeRAG",
    welcomeDesc: "Upload PDF documents and AI will automatically structure and analyze them.\\nExplore documents in hierarchical tree structure and get accurate answers.",
    shortcutKey: "Shortcut:",
    newSession: "New Session",
    typeMessage: "Type a message...",
    sessionDeleted: "Session deleted",
    analysisComplete: "Analysis completed!",
    uploadFailed: "Upload/Analysis failed",
    treeLoaded: "Tree loaded",
    treeLoadFailed: "Tree load failed",
    markdownSaved: "Saved as Markdown file",
    nodeSelected: "Node selected",
    pdfOpen: "Open PDF",
    general: "General Documents",
    medical: "Medical/Clinical",
    legal: "Legal/Contract",
    financial: "Financial/Accounting",
    academic: "Academic/Research",
    korean: "한국어 (Korean)",
    english: "English",
    japanese: "日本語 (Japanese)",
    deepTraversal: "Use Deep Traversal",
    flatMode: "Use Flat Mode",
    maxDepthDesc: "Maximum tree traversal depth (1-10)",
    maxBranchesDesc: "Number of child nodes to explore per level (1-10)",
    tip: "Tip",
    tipMessage: "Reducing depth and branches speeds up response but may limit information.",
    analyzing: "AI is analyzing the document...",
    selectedSection: "Selected Section",
    sectionDeselected: "Section deselected",
    sectionQuestion: "Ask about this section...",
    send: "Send",
    disclaimer: "AI responses are based on uploaded documents, but please verify important decisions with the original text.",
    closeTree: "Close tree",
    tipTreeClick: "Tip: Shift + Click to select section before asking",
    deleteSession: "Delete session",
    openSidebar: "Open sidebar",
    closeSidebar: "Close sidebar",
    processing: "Processing...",
    copiedToClipboard: "Copied to clipboard",
    copyFailed: "Copy failed",
    recentHistory: "Recent History",
    comparisonAnalysis: "Document Comparison Analysis",
    comparisonTarget: "Comparing",
    commonalities: "Commonalities",
    differences: "Differences",
    crossReferenceResolved: "Cross-references Resolved",
    crossReferenceDesc: "{count} references detected in question and automatically added to context",
    page: "Page",
    searchPlaceholder: "Search conversations...",
    searchResults: "Search Results",
    noSearchResults: "No results found",
    performance: "Performance Monitoring",
    totalQueries: "Total Queries",
    avgResponseTime: "Avg Response Time",
    avgContextSize: "Avg Context Size",
    deepTraversalUsage: "Deep Traversal Usage",
    recentQueries: "Recent Queries",
    tokens: "tokens",
    seconds: "sec"
  },
  ja: {
    settings: "設定",
    export: "エクスポート",
    treeStructure: "ツリー表示",
    uploadPdf: "PDF アップロード・分析",
    uploading: "アップロード中...",
    indexing: "分析中...",
    complete: "完了！",
    files: "ファイル",
    analysisSettings: "分析設定",
    documentDomain: "文書ドメイン",
    responseLanguage: "応答言語",
    useDeepTraversal: "Deep Traversal を使用",
    maxDepth: "最大深度",
    maxBranches: "ブランチ数",
    deepTraversalDesc: "ツリーを探索して関連セクションのみを選択",
    flatModeDesc: "文書全体を使用（レガシー）",
    domainOptimized: "選択したドメインに最適化された分析を提供",
    languageOptimized: "AIが選択した言語で応答します",
    newChat: "新しいチャット",
    noHistory: "履歴がありません。",
    welcomeTitle: "TreeRAG",
    welcomeDesc: "PDF文書をアップロードすると、AIが自動的に構造化して分析します。\\n階層的なツリー構造で文書を探索し、正確な回答を提供します。",
    shortcutKey: "ショートカット：",
    newSession: "新しいセッション",
    typeMessage: "メッセージを入力してください...",
    sessionDeleted: "セッションが削除されました",
    analysisComplete: "分析が完了しました！",
    uploadFailed: "アップロード/分析に失敗しました",
    treeLoaded: "ツリーをロードしました",
    treeLoadFailed: "ツリーのロードに失敗しました",
    markdownSaved: "Markdownファイルとして保存されました",
    nodeSelected: "ノードが選択されました",
    pdfOpen: "PDFを開く",
    general: "一般文書",
    medical: "医療/臨床",
    legal: "法律/契約",
    financial: "金融/財務",
    academic: "学術/研究",
    korean: "한국어 (韓国語)",
    english: "English (英語)",
    japanese: "日本語",
    deepTraversal: "Deep Traversal を使用",
    flatMode: "Flat Mode を使用",
    maxDepthDesc: "ツリー探索の最大深度 (1-10)",
    maxBranchesDesc: "レベルごとに探索する子ノード数 (1-10)",
    tip: "ヒント",
    tipMessage: "深度とブランチ数を減らすと応答速度が速くなりますが、情報が制限される場合があります。",
    analyzing: "AIが文書を分析しています...",
    selectedSection: "選択されたセクション",
    sectionDeselected: "セクション選択解除",
    sectionQuestion: "このセクションについて質問...",
    send: "送信",
    disclaimer: "AIの回答はアップロードされた文書に基づいていますが、重要な決定の際は必ず原文を再確認してください。",
    closeTree: "ツリーを閉じる",
    tipTreeClick: "ヒント: Shift + クリックでセクションを選択してから質問",
    deleteSession: "セッション削除",
    openSidebar: "サイドバーを開く",
    closeSidebar: "サイドバーを閉じる",
    processing: "処理中...",
    copiedToClipboard: "クリップボードにコピーされました",
    copyFailed: "コピー失敗",
    recentHistory: "最近の履歴",
    comparisonAnalysis: "文書比較分析",
    comparisonTarget: "比較対象",
    commonalities: "共通点",
    differences: "相違点",
    crossReferenceResolved: "クロスリファレンス解決済み",
    crossReferenceDesc: "質問から{count}個の参照が検出され、自動的にコンテキストに追加されました",
    page: "ページ",
    searchPlaceholder: "会話を検索...",
    searchResults: "検索結果",
    noSearchResults: "検索結果がありません",
    performance: "パフォーマンスモニタリング",
    totalQueries: "総質問数",
    avgResponseTime: "平均応答時間",
    avgContextSize: "平均コンテキストサイズ",
    deepTraversalUsage: "Deep Traversal 使用率",
    recentQueries: "最近の質問",
    tokens: "トークン",
    seconds: "秒"
  }
};

export type UILanguage = keyof typeof UI_TEXT;
