#!/usr/bin/env python3
"""Regenerate Figure 6 (component ablation, Table 5's four configurations) with
the same publication styling used elsewhere in the paper's figures.

The chart previously embedded as Figure 6 in the manuscript was generated by an
ad hoc, unstyled script whose source was not kept in the repo (plain matplotlib
defaults: sans-serif font, no gridlines, no edge strokes). This script rebuilds
the identical data (data/benchmark_reports/ablation_results.json, the same
numbers already reported in Table 5) using the UNIFIED_STYLE_INJECTED rcParams
block shared by scripts/plot_results.py and scripts/plot_ci_forest.py, and in
Table 5's row order (Base -> +Beam -> +Beam+Compression -> Full) rather than
score-sorted, so the figure reads left-to-right the same way the table does.

Writes data/benchmark_reports/figures/figure_6_table5_ablation.{png,pdf}.
"""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# UNIFIED_STYLE_INJECTED (matches scripts/plot_results.py, plot_ci_forest.py)
plt.rcParams.update({
    "axes.grid": True, "axes.grid.axis": "x", "grid.alpha": 0.28,
    "grid.linestyle": "-", "grid.linewidth": 0.5, "axes.axisbelow": True,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.edgecolor": "#333333", "axes.linewidth": 0.9,
    "axes.titlesize": 14, "axes.titleweight": "bold",
    "axes.labelsize": 13, "xtick.labelsize": 11, "ytick.labelsize": 11.5,
    "xtick.color": "#333333", "ytick.color": "#333333",
    "font.size": 12, "font.family": "serif",
    "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"],
    "mathtext.fontset": "dejavuserif",
    "legend.fontsize": 10.5, "legend.frameon": False,
    "savefig.dpi": 300, "figure.dpi": 300,
})

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "benchmark_reports" / "ablation_results.json"
FIGDIR = ROOT / "data" / "benchmark_reports" / "figures"

# Table-5 order and display labels (Configuration column, shortened for axis ticks)
ORDER = [
    ("cfg_base",          "Base\n(DFS, no compress, no ref)"),
    ("cfg_beam",          "+ Beam\n(no compress, no ref)"),
    ("cfg_beam_compress", "+ Beam + Compression"),
    ("cfg_full",          "Full\n(Beam + Compress + Ref)"),
]

CB_BLUE = "#0072B2"
CB_GREEN = "#009E73"


def main():
    rows = {r["id"]: r for r in json.loads(DATA.read_text())["configs"]}

    labels = [lbl for _id, lbl in ORDER]
    rouge = [rows[_id]["rouge_l"] for _id, _ in ORDER]
    delta = [rows[_id]["delta_rouge_l_vs_full"] for _id, _ in ORDER]

    y = list(range(len(ORDER)))[::-1]  # Base at top, Full at bottom (reads like the table)
    fig, ax = plt.subplots(figsize=(8, 4.2))
    colors = [CB_GREEN if _id == "cfg_full" else CB_BLUE for _id, _ in ORDER]
    bars = ax.barh(y, rouge, height=0.6, color=colors, edgecolor="black", linewidth=0.7)

    for yi, r, d in zip(y, rouge, delta):
        tag = "Full system" if abs(d) < 1e-9 else f"Δ = {d:+.3f}"
        ax.text(r + 0.008, yi, tag, va="center", fontsize=10)

    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xlabel("ROUGE-L (n = 70, General Benchmark)")
    ax.set_title("Component ablation: ROUGE-L by configuration\n(Δ = difference vs. Full System)")
    ax.set_xlim(0, max(rouge) + 0.09)
    fig.tight_layout()

    FIGDIR.mkdir(parents=True, exist_ok=True)
    for ext in ("png", "pdf"):
        fig.savefig(FIGDIR / f"figure_6_table5_ablation.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  ✓ wrote {FIGDIR / 'figure_6_table5_ablation.png'}")


if __name__ == "__main__":
    main()
